services:
  web:
    image: ${DOCKER_USER}/${DOCKER_USER}-tailadmin-laravel:beta
    ports:
      - "8090:8090"
    environment:
      DB_HOST: db
      DB_DATABASE: tailadmin
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tailadmin
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 5
      timeout: 5s
      interval: 10s
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
